package com.mycompany.finalproject;
// Evan Scully -- Car Filter Class
import com.google.gson.Gson;
import java.awt.Desktop;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/*
    This class displays a GUI application that takes in ten user inputs based on car make, min year, max year, model, zip code, distance, body style, mileage, and exterior/interior color desires.
    The user then has the option to search between four different used car websites based on their selections: Cars.com, CarMax.com, TrueCar.com, or AutoTrader.com. 
    The user may go back to the home screen or go to a favorites page where they can see all of their saved recent searches as direct links. 
*/
public class CarFilter extends javax.swing.JFrame {
    private StartScreen home;
    private Favorite favorites;
    private static String[] makeArray;   // holds all models from the allMakes.json file.
    private static ModelsListResult[] info;
    private static String[] modelArray;  // holds all models from 1992-2024.json files that correspond with the currently selected make. 
                                         // array specifically created for the use of the addJsonToComboBoxModel() method. 
    /* Constructor that creates the GUI elements for the JFrame.
       Calls addJsonToComboBoxMake to populate the comboBoxes with corresponding json files.
       Calls addJsonToComboBoxModel to populate the comboBoxes with models based on the currently selected make. The files determine what models are available. 
       Json files remain in main > resources folder.*/
    public CarFilter() {
        initComponents();
        for(int year=1992; year<2024; year++) {
            // populate jComboBoxYear with years 1992-2024 
            jComboYear.addItem(Integer.toString(year));
        }
        addJsonToComboBoxMake(getClass().getResource("/allMakes.json").getFile(), jComboBoxMake);    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboYear = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxModel = new javax.swing.JComboBox<>();
        jComboBoxMake = new javax.swing.JComboBox<>();
        homeButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxDistance = new javax.swing.JComboBox<>();
        jButtonAutoTrader = new javax.swing.JButton();
        jButtonFavorites = new javax.swing.JButton();
        jtfZipCode = new javax.swing.JTextField();
        jComboBoxMaxMileage = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxBodyStyle = new javax.swing.JComboBox<>();
        jComboBoxExtColor = new javax.swing.JComboBox<>();
        jComboBoxIntColor = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButtonSaveSearch = new javax.swing.JButton();
        jButtonCars = new javax.swing.JButton();
        jButtonTrueCar = new javax.swing.JButton();
        jButtonCarMax = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboYear.setFont(new java.awt.Font("Kohinoor Bangla", 0, 13)); // NOI18N
        /*
        jComboYear.setModel(null);
        */
        jComboYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboYearActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Kohinoor Bangla", 1, 13)); // NOI18N
        jLabel1.setText("Year");

        jLabel2.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 24)); // NOI18N
        jLabel2.setText("Car Filtered Search");

        jLabel3.setFont(new java.awt.Font("Kohinoor Bangla", 1, 13)); // NOI18N
        jLabel3.setText("Make");

        jLabel4.setFont(new java.awt.Font("Kohinoor Bangla", 1, 13)); // NOI18N
        jLabel4.setText("Model");

        jComboBoxModel.setFont(new java.awt.Font("Kohinoor Bangla", 0, 13)); // NOI18N
        /*
        jComboBoxModel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MDX" }));
        */
        jComboBoxModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxModelActionPerformed(evt);
            }
        });

        jComboBoxMake.setFont(new java.awt.Font("Kohinoor Bangla", 0, 13)); // NOI18N
        /*
        jComboBoxMake.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enter Data" }));
        */
        jComboBoxMake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMakeActionPerformed(evt);
            }
        });

        homeButton.setFont(new java.awt.Font("Kohinoor Bangla", 0, 13)); // NOI18N
        homeButton.setText("Home");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Kohinoor Bangla", 1, 13)); // NOI18N
        jLabel5.setText("Zip Code");

        jLabel6.setFont(new java.awt.Font("Kohinoor Bangla", 1, 13)); // NOI18N
        jLabel6.setText("Distance (mi)");

        jComboBoxDistance.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "50", "100", "200", "500", "1000" }));
        jComboBoxDistance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDistanceActionPerformed(evt);
            }
        });

        jButtonAutoTrader.setBackground(new java.awt.Color(255, 149, 2));
        jButtonAutoTrader.setFont(new java.awt.Font("Kohinoor Bangla", 1, 14)); // NOI18N
        jButtonAutoTrader.setForeground(new java.awt.Color(1, 33, 105));
        jButtonAutoTrader.setText("AutoTrader");
        jButtonAutoTrader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAutoTraderActionPerformed(evt);
            }
        });

        jButtonFavorites.setFont(new java.awt.Font("Kohinoor Bangla", 0, 13)); // NOI18N
        jButtonFavorites.setText("Favorites");
        jButtonFavorites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFavoritesActionPerformed(evt);
            }
        });

        jtfZipCode.setFont(new java.awt.Font("Kohinoor Bangla", 0, 13)); // NOI18N
        jtfZipCode.setText("01915");
        jtfZipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfZipCodeActionPerformed(evt);
            }
        });

        jComboBoxMaxMileage.setFont(new java.awt.Font("Kohinoor Bangla", 0, 13)); // NOI18N
        jComboBoxMaxMileage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"15000", "30000", "45000", "60000", "75000", "100000", "150,000", "200,000" , "250000"}));
        jComboBoxMaxMileage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMaxMileageActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Kohinoor Bangla", 1, 13)); // NOI18N
        jLabel8.setText("Max Mileage");

        jLabel9.setFont(new java.awt.Font("Kohinoor Bangla", 1, 13)); // NOI18N
        jLabel9.setText("Body Style");

        jComboBoxBodyStyle.setFont(new java.awt.Font("Kohinoor Bangla", 0, 13)); // NOI18N
        jComboBoxBodyStyle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SUV", "Sedan", "Coupe", "Convertible", "Truck", "Hatchback", "Van", "Wagon" }));
        jComboBoxBodyStyle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBodyStyleActionPerformed(evt);
            }
        });

        jComboBoxExtColor.setFont(new java.awt.Font("Kohinoor Bangla", 0, 13)); // NOI18N
        jComboBoxExtColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Black", "White", "Red", "Brown", "Beige", "Gray", "Silver", "Green", "Gold", "Orange", "Pink", "Yellow", "Purple" }));
        jComboBoxExtColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxExtColorActionPerformed(evt);
            }
        });

        jComboBoxIntColor.setFont(new java.awt.Font("Kohinoor Bangla", 0, 13)); // NOI18N
        jComboBoxIntColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Black", "White", "Red", "Brown", "Beige", "Gray", "Silver", "Green", "Gold", "Orange", "Pink", "Yellow", "Purple" }));
        jComboBoxIntColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxIntColorActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Kohinoor Bangla", 1, 13)); // NOI18N
        jLabel10.setText("Exterior Color");

        jLabel11.setFont(new java.awt.Font("Kohinoor Bangla", 1, 13)); // NOI18N
        jLabel11.setText("Interior Color");

        jButtonSaveSearch.setFont(new java.awt.Font("Kohinoor Bangla", 0, 13)); // NOI18N
        jButtonSaveSearch.setText("Save Search");
        jButtonSaveSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveSearchActionPerformed(evt);
            }
        });

        jButtonCars.setBackground(new java.awt.Color(62, 55, 151));
        jButtonCars.setFont(new java.awt.Font("Kohinoor Bangla", 1, 13)); // NOI18N
        jButtonCars.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCars.setText("Cars.com");
        jButtonCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarsActionPerformed(evt);
            }
        });

        jButtonTrueCar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonTrueCar.setFont(new java.awt.Font("Kohinoor Bangla", 1, 13)); // NOI18N
        jButtonTrueCar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTrueCar.setText("TrueCar");
        jButtonTrueCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTrueCarActionPerformed(evt);
            }
        });

        jButtonCarMax.setBackground(new java.awt.Color(255, 217, 0));
        jButtonCarMax.setFont(new java.awt.Font("Kohinoor Bangla", 1, 13)); // NOI18N
        jButtonCarMax.setForeground(new java.awt.Color(5, 51, 97));
        jButtonCarMax.setText("Car Max");
        jButtonCarMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarMaxActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 14)); // NOI18N
        jLabel12.setText("Select Search Site");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonFavorites)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(191, 191, 191))
            .addGroup(layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jButtonSaveSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButtonAutoTrader, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(jComboBoxMaxMileage, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxDistance, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel6))
                    .addComponent(jLabel2)
                    .addComponent(jLabel9)
                    .addComponent(jComboBoxBodyStyle, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxMake, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxExtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxIntColor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonCars, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonTrueCar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCarMax, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jComboBoxModel, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel11))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(180, 180, 180))
                            .addComponent(jComboYear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFavorites))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxDistance, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jtfZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxMake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxMaxMileage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxBodyStyle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxExtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxIntColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAutoTrader, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCars, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTrueCar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCarMax, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSaveSearch)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboYearActionPerformed
        String year = jComboYear.getSelectedItem().toString();
        // I wanted to have a min and max year, and create a list for all of the models from the files between those years, 
        // and then add that list to the combo box, but unfortunatly I ran out of time.
        addJsonToComboBoxModel(getClass().getResource("/"+year+".json").getFile(), jComboBoxModel);
    }//GEN-LAST:event_jComboYearActionPerformed

    private void jComboBoxModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxModelActionPerformed
        getSelectedStrFromComboBox(jComboBoxModel);
    }//GEN-LAST:event_jComboBoxModelActionPerformed

    private void jComboBoxMakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMakeActionPerformed
        getSelectedStrFromComboBox(jComboBoxMake);
    }//GEN-LAST:event_jComboBoxMakeActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        home = new StartScreen();
        home.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeButtonActionPerformed

    private void jButtonFavoritesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFavoritesActionPerformed
        favorites = new Favorite();
        favorites.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonFavoritesActionPerformed

    private void jtfZipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfZipCodeActionPerformed
        getZip();
    }//GEN-LAST:event_jtfZipCodeActionPerformed
    // SAVE SEARCH BUTTON - calls Favorites class constructor so it can save it into it's array and GUI over in that class.
    private void jButtonSaveSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveSearchActionPerformed
        // when clicked, whatever is currently selected in make, model, zip and distance 
        //will be put into the URl and added to favorites.
        String make = getSelectedStrFromComboBox(jComboBoxMake).replace(' ', '_').replace('-', '_').toLowerCase();
        String model = getSelectedStrFromComboBox(jComboBoxModel).replace(' ', '_').replace('-', '_').toLowerCase();
        int year = getYear();
        int distance = getSelectedIntFromComboBox(jComboBoxDistance, 5);
        String zipCode = getZip();
        String url = "https://www.cars.com/shopping/results/?dealer_id=&keyword=&list_price_max=&list_price_min=&makes[]="+make+"&maximum_distance="+distance+"&mileage_max=&models[]="+make+"-"+model+"&monthly_payment=&page_size=20&sort=best_match_desc&stock_type=all&year_max="+year+"&year_min="+year+"&zip="+zipCode;
        Favorite addToFavoritesList = new Favorite(url);        
        addToFavoritesList.add();
    }//GEN-LAST:event_jButtonSaveSearchActionPerformed
    // AUTOTRADER
    private void jButtonAutoTraderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAutoTraderActionPerformed
        String make = getSelectedStrFromComboBox(jComboBoxMake).replace(' ', '_').replace('-', '_').toLowerCase();
        if(getSelectedStrFromComboBox(jComboBoxModel) == null) {
            JOptionPane.showMessageDialog(null, "Must select a model! Select a mode & year to select a model. ");
            return;
        }
        String model = getSelectedStrFromComboBox(jComboBoxModel).replace(' ', '_').replace('-', '_').toLowerCase();
        int year = getYear();
        int distance = getSelectedIntFromComboBox(jComboBoxDistance, 5);
        String zipCode = getZip();
        int maxMileage = getSelectedIntFromComboBox(jComboBoxMaxMileage, 250000);
        String bodyStyle = getSelectedStrFromComboBox(jComboBoxBodyStyle).toLowerCase();
        if("suv".equals(bodyStyle)) {
            bodyStyle = "suv-crossover";
        }
        String extColor = getSelectedStrFromComboBox(jComboBoxExtColor).toLowerCase();
        String intColor = getSelectedStrFromComboBox(jComboBoxIntColor).toLowerCase();
        String url = "https://www.autotrader.com/cars-for-sale/all-cars/"+bodyStyle+"/"+year+"/"+make+"/"+model+"/"+zipCode+"?endYear="+year+"&extColorsSimple="+extColor.toUpperCase()+"&interiorColorsSimple="+intColor.toUpperCase()+"&isNewSearch=true&maxMileage="+maxMileage+"&searchRadius="+distance+"&zip="+zipCode;
        try {
            openWebpage(new URI(url)); 
        } catch (URISyntaxException e) {
            JOptionPane.showMessageDialog(null, "Error opening the url");
        }
    }//GEN-LAST:event_jButtonAutoTraderActionPerformed

    private void jComboBoxDistanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDistanceActionPerformed
        getSelectedIntFromComboBox(jComboBoxDistance, 5);
    }//GEN-LAST:event_jComboBoxDistanceActionPerformed
    // CARS.COM
    private void jButtonCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarsActionPerformed
        String make = getSelectedStrFromComboBox(jComboBoxMake).replace(' ', '_').replace('-', '_').toLowerCase();
        if(getSelectedStrFromComboBox(jComboBoxModel) == null) {
            JOptionPane.showMessageDialog(null, "Must select a model! Select a mode & year to select a model. ");
            return;
        }
        String model = getSelectedStrFromComboBox(jComboBoxModel).replace(' ', '_').replace('-', '_').toLowerCase();
        int year = getYear();
        int distance = getSelectedIntFromComboBox(jComboBoxDistance, 5);
        String zipCode = getZip();
        int maxMileage = getSelectedIntFromComboBox(jComboBoxMaxMileage, 250000);
        String bodyStyle = getSelectedStrFromComboBox(jComboBoxBodyStyle).toLowerCase();
        String extColor = getSelectedStrFromComboBox(jComboBoxExtColor).toLowerCase();
        String intColor = getSelectedStrFromComboBox(jComboBoxIntColor).toLowerCase();
        String url = "https://www.cars.com/shopping/results/?body_style_slugs[]="+bodyStyle+"&dealer_id=&exterior_color_slugs[]="+extColor+"&interior_color_slugs[]="+intColor+"&keyword=&list_price_max=&list_price_min=&makes[]="+make+"&maximum_distance="+distance+"&mileage_max="+maxMileage+"&models[]="+make+"-"+model+"&monthly_payment=&page_size=20&sort=best_match_desc&stock_type=all&year_max="+year+"&year_min="+year+"&zip="+zipCode;
        try {
            openWebpage(new URI(url)); 
        } catch (URISyntaxException e) {
            JOptionPane.showMessageDialog(null, "Error opening the url");
        }
    }//GEN-LAST:event_jButtonCarsActionPerformed

    private void jComboBoxMaxMileageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMaxMileageActionPerformed
        getSelectedIntFromComboBox(jComboBoxMaxMileage, 250000);
    }//GEN-LAST:event_jComboBoxMaxMileageActionPerformed

    private void jComboBoxBodyStyleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBodyStyleActionPerformed
        getSelectedStrFromComboBox(jComboBoxBodyStyle);
    }//GEN-LAST:event_jComboBoxBodyStyleActionPerformed

    private void jComboBoxExtColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxExtColorActionPerformed
        getSelectedStrFromComboBox(jComboBoxExtColor);
    }//GEN-LAST:event_jComboBoxExtColorActionPerformed

    private void jComboBoxIntColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxIntColorActionPerformed
        getSelectedStrFromComboBox(jComboBoxIntColor);
    }//GEN-LAST:event_jComboBoxIntColorActionPerformed
    // TRUE CAR
    private void jButtonTrueCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTrueCarActionPerformed
        String make = getSelectedStrFromComboBox(jComboBoxMake).replace(' ', '_').replace('-', '_').toLowerCase();
        if(getSelectedStrFromComboBox(jComboBoxModel) == null) {
            JOptionPane.showMessageDialog(null, "Must select a model! Select a mode & year to select a model. ");
            return;
        }
        String model = getSelectedStrFromComboBox(jComboBoxModel).replace(' ', '_').replace('-', '_').toLowerCase();
        int year = getYear();
        int distance = getSelectedIntFromComboBox(jComboBoxDistance, 5);
        String zipCode = getZip();
        int maxMileage = getSelectedIntFromComboBox(jComboBoxMaxMileage, 250000);
        String bodyStyle = getSelectedStrFromComboBox(jComboBoxBodyStyle).toLowerCase();
        String extColor = getSelectedStrFromComboBox(jComboBoxExtColor).toLowerCase();
        String intColor = getSelectedStrFromComboBox(jComboBoxIntColor).toLowerCase();
        String url = "https://www.truecar.com/used-cars-for-sale/listings/"+make+"/"+model+"/year-"+year+"/body-"+bodyStyle+"/location-"+zipCode+"/?exteriorColorGeneric[]="+extColor+"&interiorColorGeneric[]="+intColor+"&mileageHigh="+maxMileage+"&searchRadius="+distance;
        try {
            openWebpage(new URI(url)); 
        } catch (URISyntaxException e) {
            JOptionPane.showMessageDialog(null, "Error opening the url");
        }
    }//GEN-LAST:event_jButtonTrueCarActionPerformed
    
    // CAR MAX
    private void jButtonCarMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarMaxActionPerformed
        String make = getSelectedStrFromComboBox(jComboBoxMake).replace(' ', '_').replace('-', '_').toLowerCase();
        if(getSelectedStrFromComboBox(jComboBoxModel) == null) {
            JOptionPane.showMessageDialog(null, "Must select a model! Select a mode & year to select a model. ");
            return;
        }
        String model = getSelectedStrFromComboBox(jComboBoxModel).replace(' ', '_').replace('-', '_').toLowerCase();
        int year = getYear();
        int maxMileage = getSelectedIntFromComboBox(jComboBoxMaxMileage, 250000);
        String bodyStyle = getSelectedStrFromComboBox(jComboBoxBodyStyle).toLowerCase();
        String extColor = getSelectedStrFromComboBox(jComboBoxExtColor).toLowerCase();
        String intColor = getSelectedStrFromComboBox(jComboBoxIntColor).toLowerCase();
        String url = "https://www.carmax.com/cars/"+make+"/"+model+"/"+bodyStyle+"/"+extColor+"/interiorcolor-"+intColor+"?year="+year+"-"+year+"&mileage="+maxMileage+"";
        try {
            openWebpage(new URI(url)); 
        } catch (URISyntaxException e) {
            JOptionPane.showMessageDialog(null, "Error opening the url");
        }
    }//GEN-LAST:event_jButtonCarMaxActionPerformed
    private String getZip() {
        //if selectedItem() is more or less than 5 digits, throw an error message
        String zipCode = jtfZipCode.getText();
        if(isValidZip(zipCode)) { 
            return zipCode;
        } else {
            JOptionPane.showMessageDialog(null, "Error opening the file");
            return "01752";
        }
    }
    public static boolean isValidZip(String input) {
        // https://stackoverflow.com/questions/23093808/check-if-a-string-consists-of-exactly-5-digits-in-java
        // \\d{5} represents a five digit number.
        String regex = "\\d{5}";
        // Create a Pattern object
        Pattern pattern = Pattern.compile(regex);
        // Create a Matcher object
        Matcher matcher = pattern.matcher(input);
        // Check if the string matches the pattern
        return matcher.matches();
    }
    
    private int getYear() {
        return getSelectedIntFromComboBox(jComboYear, 1992);
    }

    /* method: finds the selected String item in the given jComboBox. 
       parameters: jComboBox
       returns: (String) returns the currently selected String item in a jComboBox.
    */ 
    private String getSelectedStrFromComboBox(JComboBox jComboBox) {
        Object selectedItem = jComboBox.getSelectedItem();
        String selectedItemStr;
        if (selectedItem != null) {
            selectedItemStr = selectedItem.toString();
            return selectedItemStr;
        } else {
            return null;
        }
    }
    /* method: finds the selected int item in the given jComboBox. 
       parameters: jComboBox, elseNum - a number if nothing is selected.
       returns: (int) returns the currently selected int item in a jComboBox.
    */     
    private int getSelectedIntFromComboBox(JComboBox jComboBox, int elseNum) {
        Object selectedItem = jComboBox.getSelectedItem();
        String selectedItemStr = selectedItem.toString();
        int selectedItemInt;
        if (selectedItem != null) {
            selectedItemInt = Integer.parseInt(selectedItemStr);
            return selectedItemInt;
        } else {
            return elseNum;
        }
    }
    /* method: opens a web page in a browser. 
       parameters: passed in URL link
       returns: void
    */          
    private static void openWebpage(URI uri) {
        if(Desktop.isDesktopSupported() && Desktop.getDesktop().isSupported(Desktop.Action.BROWSE)) {
            try {
                Desktop.getDesktop().browse(uri);
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "Error opening the file");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Desktop browsing is not supported on this platform.");
        }
    }
    
    /* method: takes in a relative file path of json file, reads in data, and adds the whole array into a j-combo-box.
               the make data was copied from the makes of cars.com in the inspect section, formatted in vscode from csv to json, and brought into Netbeans for usage.
       parameters: filePath to data files, jComboBox.
       returns: void.
    */
    private void addJsonToComboBoxMake(String filePath, JComboBox jComboBox) {                                        
        FileReader fr;
        try {
            File f = new File(filePath);
            if(!f.exists()) {   // if file doesn't exist throw error message
                JOptionPane.showMessageDialog(null, "Error opening the file");
            }
            fr = new FileReader(f); // if the file exists, initialize FileReader.
            Gson gson = new Gson();
            makeArray = gson.fromJson(fr, String[].class);  // use Gson class constructor to grab string array data from the file.
            jComboBox.setModel(new DefaultComboBoxModel(makeArray)); // converted string array to DefaultComboBoxModel because ComboBoxModel is an interface class.
                                                                          // setModel puts data into the combobox specified.
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error opening the file: " + ex.getMessage());
        }
    }
    /* method: uses data from the following API/github repository, downloaded in Vscode, edited using Name: CSV to JSON Converter and  
               Edit CSV file https://marketplace.visualstudio.com/items?itemName=janisdd.vscode-edit-csv
               CSV to Json file Converter: (https://marketplace.visualstudio.com/items?itemName=Chukwuamaka.csvtojson-converter)
               Github Repo/API link: https://github.com/abhionlyone/us-car-models-data
               The models data was downloaded from a source unrelated to the used car searching websites, 
               so formatting was done to make the makes align 100% and models align 90%.
       parameters: filePath to data files, jComboBox.
       returns: void.
    */       
    private void addJsonToComboBoxModel(String filePath, JComboBox jComboBox) {
        FileReader fr;
        try {
            File f = new File(filePath);
            if(!f.exists()) {   // if file doesn't exist throw error message
                JOptionPane.showMessageDialog(null, "Error opening the file");
            }
            fr = new FileReader(f); // if the file exists, initialize FileReader.
            Gson gson = new Gson();
            
            info = gson.fromJson(fr, ModelsListResult[].class);
            ArrayList<String> modelArrayList = new ArrayList<>(); // initialize and declare an ArrayList to hold all of the Strings from the desired objects from the file. 
            String make = getSelectedStrFromComboBox(jComboBoxMake);
            for (ModelsListResult each : info) {     // loop through info objects that each hold year, make, model (all objects in the list and are of type ModelsListResult).
                if(each.make.equals(make)) {  // check if the corresponding selected make in jComboBoxMake is the same as the make in the object from the file.
                    modelArrayList.add(each.model);  // add model that corresponds with the make in that object.
                }
            }
            modelArray = modelArrayList.toArray(String[]::new);
            jComboBox.setModel(new DefaultComboBoxModel(modelArray)); // converted string array to DefaultComboBoxModel because ComboBoxModel is an interface class.
           
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error opening the file: " + ex.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarFilter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarFilter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarFilter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarFilter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarFilter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton homeButton;
    private javax.swing.JButton jButtonAutoTrader;
    private javax.swing.JButton jButtonCarMax;
    private javax.swing.JButton jButtonCars;
    private javax.swing.JButton jButtonFavorites;
    private javax.swing.JButton jButtonSaveSearch;
    private javax.swing.JButton jButtonTrueCar;
    private javax.swing.JComboBox<String> jComboBoxBodyStyle;
    private javax.swing.JComboBox<String> jComboBoxDistance;
    private javax.swing.JComboBox<String> jComboBoxExtColor;
    private javax.swing.JComboBox<String> jComboBoxIntColor;
    private javax.swing.JComboBox<String> jComboBoxMake;
    private javax.swing.JComboBox<String> jComboBoxMaxMileage;
    private javax.swing.JComboBox<String> jComboBoxModel;
    private javax.swing.JComboBox<String> jComboYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtfZipCode;
    // End of variables declaration//GEN-END:variables
}
