package com.mycompany.finalproject;
// Evan Scully -- Start Screen Class for Car Finder Application.
/*HOURS:
 10/24 -- 1 hour -- started coding and researching how to add JCheckBox and filter boxes using JPanel.
 10/26 -- 2 hours -- found CIS Automotive API and researched how to implement it and what it does.
 10/30 -- 1 hour -- looked into the Edmunds API. Considering downloading car data to reutrn it to the user after filters are plugged in.
 11/1 -- 1 hour -- discussed API and project updates with Prof Ocean
 11/17 -- 1 hour -- downloaded csv data
 11/21 -- 4 hours - redesign and figure out how to switch between different jpanels in diff classes, searched for API
 11/22 -- 2 hours - got an API with all car models. Wasn't able to make them print, but wrote code close to do so.
 11/26 -- 2 hours - researched more on how to fix the API (problem with loading the API data)
 11/27 -- 1 hour - fixed fonts and design
 11/29 -- 3 hours - [office hours] set up "blue print" - download makes, connect models online, and use autotrader for browser search link (I will research this). 
 11/30 -- 6 hours - worked on adding for loop for years list to JLabels, downloaded zip csv files, created new URLBuilder classes, and worked on code in general
 12/1 --  4 hours - continued to add filters to car filter and researching how to parse and serialize json files to jcombobox.
 12/3 -- 5.5 hours - created favorites jlabel and class, continued researching how to throw json data into jcombobox - serialization needed for this? Creating abstract class necessary?
 12/4 -- 6 hours - worked on addJsonToComboBox method.
 12/5 -- 5 hours - finishing up Favorites class and still stuck on getting data from json files for makes and models
 12/8 -- 6 hours - worked on cleaning up looks and functionality of GUI, and moved json files from vscode to netbeans folder for easier access.
 12/9 -- 5 hours - added comments, added favorites things, worked on populating models
 12/10 -- 3 hours - fixed links for all four buttons, fixed errors in code
 12/11 -- 4 hours - finished code that adds models to their boxes / years click chages model selections
 12/13 -- 3 hours - all testing / made code more efficient - no static's
 12/14 -- 4 hours - fixed the favorites class / slides / final touches / testing
  Total: 69.5 hours
*/
/*
This program takes in filtered data from the user and outputs links to used car websites based on those filters. 
*/
public class StartScreen extends javax.swing.JFrame {
    private QuickSearch quickSearchScreen;
    private CarFilter carFilterScreen;
    private Favorite favoritesScreen;

    public StartScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        FilterSearchButton = new javax.swing.JButton();
        QuickSearchButton = new javax.swing.JButton();
        jButtonSavedSearches = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Hiragino Mincho ProN", 2, 48)); // NOI18N
        jLabel1.setText("USED CAR FINDER");

        FilterSearchButton.setBackground(new java.awt.Color(245, 245, 245));
        FilterSearchButton.setFont(new java.awt.Font("Kohinoor Bangla", 1, 14)); // NOI18N
        FilterSearchButton.setText("Filter Search");
        FilterSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilterSearchButtonActionPerformed(evt);
            }
        });

        QuickSearchButton.setBackground(new java.awt.Color(245, 245, 245));
        QuickSearchButton.setFont(new java.awt.Font("Kohinoor Bangla", 1, 14)); // NOI18N
        QuickSearchButton.setText("Quick Search");
        QuickSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuickSearchButtonActionPerformed(evt);
            }
        });

        jButtonSavedSearches.setFont(new java.awt.Font("Kohinoor Bangla", 0, 13)); // NOI18N
        jButtonSavedSearches.setText("Saved Searches");
        jButtonSavedSearches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSavedSearchesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(QuickSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(FilterSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jButtonSavedSearches, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FilterSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QuickSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jButtonSavedSearches)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // these next three functions open and closed GUI tabs for the ones that have setVisible(true).
    private void QuickSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuickSearchButtonActionPerformed
        // go to QuickSearch.java screen
        quickSearchScreen = new QuickSearch();
        quickSearchScreen.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_QuickSearchButtonActionPerformed

    private void FilterSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilterSearchButtonActionPerformed
        // go to CarFilter.java screen
        carFilterScreen = new CarFilter();
        carFilterScreen.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_FilterSearchButtonActionPerformed
    
    private void jButtonSavedSearchesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSavedSearchesActionPerformed
        favoritesScreen = new Favorite();
        favoritesScreen.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonSavedSearchesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//        QuickSearch option1 = new QuickSearch();
//        option1.caller();
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FilterSearchButton;
    private javax.swing.JButton QuickSearchButton;
    private javax.swing.JButton jButtonSavedSearches;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
